### ISSUE TITLE
Creando usuario inactivo

### ISSUE THREAD

**Issue by ESRomero** [FruitParty/Proyecto_RRHH#3]
No debe estar eso de estado cuando se activa, entra activo de una pidió el ing

**Comment by FruitParty** [comment]
Esto falta

**Comment by AnthonyWRodriguez** [comment]
Facil, solo se elimina el cmb y el label y en el procedimiento se manda un 0, asi siempre esta activo

**Comment by AnthonyWRodriguez** [comment]
Ya esta corregido en mi version
